<?
$PERM["/"]["*"]="R";
$PERM["/"]["G5"]="W";
$PERM["index.php"]["G5"]="W";
$PERM["partners"]["*"]="D";
$PERM["partners"]["G6"]="R";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
?>