<?if(!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true)die();?>
<?$APPLICATION->IncludeComponent(
	"bitrix:infoportal.element.add.form",
	"",
	Array(
		"SEF_MODE" => $arParams["SEF_MODE"],
		"LIST_URL" => $arResult["FOLDER"].$arResult["URL_TEMPLATES"]["afisha"],
		"USER_MESSAGE_EDIT" => "Фильм успешно сохранен",
		"USER_MESSAGE_ADD" => "Фильм успешно добавлен",
		"IBLOCK_TYPE" => $arParams["IBLOCK_TYPE"],
		"IBLOCK_ID" => $arParams["IBLOCK_ID"],
		"PROPERTY_CODES" => array("NAME", "DETAIL_PICTURE", "ACTIVE", "DATE_ACTIVE_FROM", "DATE_ACTIVE_TO", "DETAIL_TEXT"),
		"PROPERTY_CODES_REQUIRED" => array("NAME"),
		"GROUPS" => $arParams["ADD_GROUP_PERMISSIONS"],
		"STATUS_NEW" => "N",
		"STATUS" => "ANY",
		"ELEMENT_ASSOC" => "CREATED_BY",
		"MAX_USER_ENTRIES" => "100000",
		"MAX_LEVELS" => "100000",
		"LEVEL_LAST" => "N",
		"USE_CAPTCHA" => "N",
		"DEFAULT_INPUT_SIZE" => "50",
		"RESIZE_IMAGES" => "Y",
		"MAX_FILE_SIZE" => "0",
		"PREVIEW_TEXT_USE_HTML_EDITOR" => "N",
		"DETAIL_TEXT_USE_HTML_EDITOR" => "Y",
		"CUSTOM_TITLE_NAME" => "Название фильма",
		"CUSTOM_TITLE_TAGS" => "",
		"CUSTOM_TITLE_DATE_ACTIVE_FROM" => "Начало проката",
		"CUSTOM_TITLE_DATE_ACTIVE_TO" => "Окончание проката",
		"CUSTOM_TITLE_IBLOCK_SECTION" => "Жанр",
		"CUSTOM_TITLE_PREVIEW_TEXT" => "",
		"CUSTOM_TITLE_PREVIEW_PICTURE" => "",
		"CUSTOM_TITLE_DETAIL_TEXT" => "Описание",
		"CUSTOM_TITLE_DETAIL_PICTURE" => "Плакат",
	),
	$component
);?>